database:
  user: some_user
  host: localhost


bitvavo:
  websocket_url: "wss://ws.bitvavo.com/v2/"
  pairs:
    - BTC-EUR
    - ETH-EUR
    - XRP-EUR
    - DOGE-EUR
    - SOL-EUR
    - ADA-EUR
    - TRX-EUR
    - SPX-EUR
    - BNB-EUR
    - XVG-EUR
    - LTC-EUR
    - XLM-EUR
    - PEPE-EUR
    - LINK-EUR
    - UNI-EUR
    - ATOM-EUR

# [OPTIONEEL, net als voorheen]
intervals:
  - "5m"
  - "15m"
  - "1h"
  - "4h"
  - "1d"


### PULLBACK_ACCUMULATE_STRATEGY ###
pullback_accumulate_strategy:
  # STAP 1 DE GROTE TREND: CHECK DIRECTION
  daily_bull_rsi: 50
  daily_bear_rsi: 50
  h4_bull_rsi: 50
  h4_bear_rsi: 50

  # Deze bestonden al (voorbeeld) gaat om de pullback 15M candle:
  rsi_bull_threshold: 40   # RSI >= 40 => oversold => bullisch pullback
  rsi_bear_threshold: 60   # RSI <= 60 => overbought => bearisch pullback

  # Nieuw (om depth_score-checks te configureren!)
  depth_threshold_bull: -0.3 # orderboek-analyse om te checken of er voldoende volume is om een trend te ondersteuen idealiter > 0)
  depth_threshold_bear: 0.3

  macd_bull_threshold: -1  # was 0
  macd_bear_threshold: 1   # was 0

  # bepaald hoever de pullback van de weerstand of support ,oet bewegen om in te stappen = pullback = true
  pullback_threshold_pct: 1.0 # is redelijk

  ml_model_enabled: true

  main_timeframe: "1h"
  trend_timeframe: "4h"
  entry_timeframe: "5m"
  daily_timeframe: "1d"
  flash_crash_timeframe: "5m"
  atr_window: 14
  accumulate_threshold: 1.0
  position_size_pct: 0.05
  tp1_atr_mult: 0.5
  tp2_atr_mult: 1.0
  trail_atr_mult: 0.5
  initial_capital: 100
  # max_daily_loss_pct: 7.5
  # flash_crash_drop_pct: 10.0
  use_depth_trend: true
  pivot_points_window: 20
  rsi_window: 14
  pullback_rolling_window: 10
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  ml_model_path: "models/pullback_model.pkl"
  stop_loss_pct: 0.015 #0.001 is 1%

ml_engine:
  model_path: "models/pullback_model.pkl"

ml_settings:
  auto_overwrite_params: false


#### BREAKOUT STRATEGY ####
breakout_strategy:
  log_file: "logs/breakout_strategy.log"
  daily_timeframe: "1d"
  main_timeframe: "4h"
  lookback_candles: 20
  breakout_buffer_pct: 0.5
  volume_threshold_factor: 1.2
  rsi_bull_level: 55
  rsi_bear_level: 45
  atr_window: 14
  sl_atr_mult: 1.0
  trail_atr_mult: 1.0
  partial_tp_r: 1.0
  partial_tp_pct: 0.25
  position_size_pct: 0.05
  max_positions_equity_pct: 0.5
  initial_capital: 100


kraken:
  # <--- Nieuwe opzet: alleen 'pairs' en intervals.
  # Als je private WS wilt, kun je hier ook 'apiKey: ...' en 'apiSecret: ...' toevoegen.
  pairs:
    - XBT-EUR
    - ETH-EUR
    - XRP-EUR
    - XDG-EUR
    - ADA-EUR
    - SOL-EUR
    - DOT-EUR
    - MATIC-EUR
    - TRX-EUR
    - LTC-EUR
    - LINK-EUR
    - XLM-EUR
    - UNI-EUR
    - ATOM-EUR
    - ALGO-EUR
    - AAVE-EUR
    - ETC-EUR
    - SAND-EUR
    - AVAX-EUR
    - BCH-EUR

  # intervals
  intervals_realtime:
    - 15
  intervals_poll:
    - 1
    - 5
    - 15
    - 60
    - 240
    - 1440
  poll_interval_seconds: 30

### Altcoin "Momentum/RotationScanner"-strategy ###
altcoin_scanner_strategy:
  enabled: true
  log_file: "logs/altcoin_scanner_strategy.log"

  # Je kunt eventueel BTC-EUR / ETH-EUR uitsluiten, of andere "large caps".
  exclude_symbols: ["BTC-EUR", "ETH-EUR", "XRP-EUR"]

  # Scanner-instellingen
  timeframe: "15m"
  lookback: 6
  price_change_threshold: 5.0
  volume_threshold_factor: 1.5
  min_base_volume: 5000

  # Positie-management
  position_size_pct: "0.05"
  max_positions_equity_pct: "0.50"
  sl_pct: 2.0
  tp_pct: 4.0
  trailing_enabled: true
  trailing_pct: 2.0

  partial_tp_enabled: true
  partial_tp_pct: 0.25

  initial_capital: 100

### MELTDOWN MANAGER ###
meltdown_manager:
  daily_loss_pct: 20              # meltdown als daily portfolio drop >= 20%
  flash_crash_pct: 20             # meltdown als >=2 coins > 20% daling
  rsi_reentry_threshold: 30       # meltdown eindigt als RSI > 30
  meltdown_coins: ["BTC-EUR", "XRP-EUR", "ETH-EUR"]   # barometer
  meltdown_coins_needed: 2        # min. 2 coins in meltdown_coins >= flash_crash_pct => meltdown
  meltdown_tf: "5m"               # timeframe voor flash crash check
  meltdown_lookback: 3            # #candles om te vergelijken (bv. 3x 5m => ~15m)


### SCALPING STRATEGY ###
scalping:
  stop_loss_pct: 0.0075
  tp1_pct: 0.03
  tp2_pct: 0.05
  rsi_lower: 40
  rsi_upper: 60
  use_trailing_for_last25: true
  volatility_threshold: 0.0
  volume_factor: 0.0
